FROM python:3.10-slim

WORKDIR /app

# Copie des fichiers
COPY . .

# Installation des dépendances
RUN pip install --upgrade pip && pip install -r requirements.txt

# Permissions pour le script de démarrage
RUN chmod +x startup.sh

# Port exposé
EXPOSE 80
EXPOSE 8501

# Script de démarrage
CMD ["./startup.sh"]
