name: Build and Deploy to Azure App Service (via ACR)

on:
  push:
    branches:
      - analyse_sentiments
  workflow_dispatch:

env:
  ACR_NAME: module7
  ACR_LOGIN_SERVER: module7.azurecr.io
  IMAGE_NAME: analyse-de-sentiments
  WEBAPP_NAME: Analyse-de-sentiments

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}       # <— on passe ici le JSON strict

      - name: Login to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build . --tag ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure Web App (via ACR)
        uses: azure/webapps-deploy@v3
        with:
          app-name:    ${{ env.WEBAPP_NAME }}
          images:      ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
