name: Deploy FastAPI to Azure Web App - Module-7

on:
  push:
    branches:
      - analyse_sentiments  # Branche qui déclenche le déploiement
  workflow_dispatch:        # Permet de lancer manuellement depuis GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Zip application files
        run: |
          zip -r app.zip app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Module-7'  # ← EXACTEMENT comme dans Azure (respecter les majuscules/minuscules)
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
