name: Build and deploy Python app to Azure Web App - Module-7

on:
  push:
    branches:
      - analyse_sentiments
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt  # ✅ si ton requirements.txt est dans le dossier `app/`

      - name: Zip application files
        run: |
          zip -r app.zip app -x "app/venv/*" "app/.venv/*" "app/__pycache__/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Module-7'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
