name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - analyse_sentiments

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Zip application files
        run: |
          zip -r app.zip app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'module-7-bgg7hvanhddthjh4'        # ← Doit matcher exactement le nom de votre App Service
          slot-name: 'production'              # ← Laissez vide pour le slot “production” par défaut
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
